---
- name: Remediation - Update Partition
  hosts: all
  connection: local
  gather_facts: no

  vars:
    vg_name: vg_root
    lv_name: lv_var
    extend_size: 5G
    # This is the message your Agent expects
    success_msg: "Success: Partition cleared. CPU utilization has dropped to 12%"

  tasks:
    # ---------------------------------------------------------
    # Step 1: Detect the Issue
    # ---------------------------------------------------------
    - name: Check current CPU utilization
      shell: echo "96"
      register: cpu_usage

    - name: Alert - High CPU Detected
      debug:
        msg: "ALERT: Current CPU utilization is {{ cpu_usage.stdout }}%. Threshold exceeded."

    # ---------------------------------------------------------
    # Step 2: Fix the Issue (Simulated)
    # ---------------------------------------------------------
    - name: Extend Logical Volume
      debug:
        msg: "Executing: lvextend -L +{{ extend_size }} /dev/{{ vg_name }}/{{ lv_name }} ... SUCCESS. Volume extended."

    - name: Resize Filesystem
      debug:
        msg: "Executing: resize2fs /dev/{{ vg_name }}/{{ lv_name }} ... SUCCESS. Filesystem resized."

    # ---------------------------------------------------------
    # Step 3: Return Data to Salesforce
    # ---------------------------------------------------------
    
    # METHOD A: Print it to the logs (The Agent can read the last line)
    - name: Final Output for Agent
      debug:
        msg: "{{ success_msg }}"

    # METHOD B: Create an API Artifact (Cleaner for Flow variables)
    # This creates a variable 'agent_response' accessible in the Job Details
    - name: Pass Success Message to Controller
      set_stats:
        data:
          agent_response: "{{ success_msg }}"
          remediation_status: "Resolved"
