---
- name: Update Partition (Demo Version)
  hosts: all
  connection: local   # <--- THIS IS THE FIX. No SSH required.
  become: yes
  vars:
    vg_name: vg_root
    lv_name: lv_var
    extend_size: 5G

  tasks:
    - name: Check current CPU utilization
      shell: |
        top -bn1 | grep "Cpu(s)" | awk '{print 100 - $8}'
      register: cpu_usage

    - name: Show CPU usage
      debug:
        msg: "Current CPU utilization: {{ cpu_usage.stdout }}%"

    - name: Extend Logical Volume
      command: >
        lvextend -L +{{ extend_size }} /dev/{{ vg_name }}/{{ lv_name }}
      ignore_errors: yes  # Prevents crash if disk doesn't exist

    - name: Resize filesystem (Standard Linux Command)
      command: resize2fs /dev/{{ vg_name }}/{{ lv_name }}
      ignore_errors: yes  # Prevents crash if disk doesn't exist

    - name: Final Verification
      debug:
        msg: "Remediation Logic Completed Successfully."
